# Generated by Django 4.0.3 on 2022-04-05 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default=' ', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dia_pagar', models.IntegerField(default=15)),
                ('quincena', models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Ambas')], default=1)),
                ('monto2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dia_pagar2', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='tipos',
            fields=[
                ('tipo', models.CharField(default=' ', max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default=' ', max_length=20)),
                ('busqueda', models.CharField(choices=[('Fijo', 'Fijo'), ('Factura', 'Factura'), ('Credito Tienda', 'Credito Tienda'), ('Tarjeta de Credito', 'Tarjeta de Credito'), ('Banco', 'Banco'), ('Credito', 'Credito')], default='Fijo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tarjetas_credito',
            fields=[
                ('numerotc', models.CharField(default=' ', max_length=20, primary_key=True, serialize=False)),
                ('nombretc', models.CharField(default=' ', max_length=30)),
                ('banco', models.CharField(choices=[('Bradescard', 'Bradescard'), ('BBVA', 'BBVA'), ('Santander', 'Santander'), ('City Banamex', 'City Banamex'), ('American Express', 'American Express')], default=' ', max_length=30)),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('dia_corte', models.IntegerField(default=1)),
                ('dia_pagar_antes', models.IntegerField(default=1)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image', models.ImageField(default='/tarjetas/default.jpg', upload_to='tarjetas')),
                ('pago_proyectado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pago_proyectado2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pago_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clave', models.ForeignKey(limit_choices_to={'tipo': 'C'}, on_delete=django.db.models.deletion.CASCADE, to='registro.gastos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('cod_credito', models.IntegerField(default=0)),
                ('factura', models.CharField(default=' ', max_length=15)),
                ('numerotc', models.CharField(default=' ', max_length=20)),
                ('forma_de_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Pago en Linea', 'Pago en Linea'), ('Pago en Tienda', 'Pago en Tienda'), ('Pago en Farmacia', 'Pago en Farmacia')], default='Pago en Linea', max_length=20)),
                ('monto_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('folio', models.CharField(default=' ', max_length=15)),
                ('clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.gastos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movimientos_tc',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('numerotc', models.CharField(default=' ', max_length=20)),
                ('tipo_mov', models.CharField(choices=[('Pago', 'Pago'), ('Compra', 'Compra'), ('Intereses', 'Intereses'), ('IVA', 'IVA'), ('Anualidad', 'Anualidad')], default='Compra', max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(default='compra', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='maestro',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=1)),
                ('quincena', models.CharField(max_length=1)),
                ('mes', models.CharField(max_length=2)),
                ('ano', models.IntegerField()),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tipos'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='factura_gastos',
            fields=[
                ('factura', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagada', models.CharField(default=0, max_length=1)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='/facturas/default.jpg', upload_to='facturas')),
                ('forma_de_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Pago en Linea', 'Pago en Linea'), ('Pago en Tienda', 'Pago en Tienda'), ('Pago en Farmacia', 'Pago en Farmacia')], max_length=20)),
                ('folio', models.CharField(max_length=15)),
                ('quincena', models.IntegerField(default=1)),
                ('clave', models.ForeignKey(limit_choices_to={'tipo': 'B'}, on_delete=django.db.models.deletion.CASCADE, to='registro.gastos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='entidad',
            fields=[
                ('cod_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=30)),
                ('image', models.ImageField(default='/entidad/default.jpg', upload_to='entidad')),
                ('clave', models.ForeignKey(limit_choices_to={'tipo': 'D'}, on_delete=django.db.models.deletion.CASCADE, to='registro.gastos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_creditos',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('cod_credito', models.IntegerField()),
                ('numero_cuota', models.IntegerField()),
                ('mes', models.IntegerField(default=1)),
                ('ano', models.IntegerField(default=2021)),
                ('pagada', models.CharField(default=0, max_length=1)),
                ('fecha_pago', models.DateField(null=True, verbose_name='Fecha de Pago')),
                ('folio', models.CharField(default=' ', max_length=15)),
                ('forma_de_pago', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Pago en Linea', 'Pago en Linea'), ('Pago en Tienda', 'Pago en Tienda'), ('Pago en Farmacia', 'Pago en Farmacia')], default='Pago en Linea', max_length=20)),
                ('monto_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abono_a_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_intereses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amortiza', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='creditos',
            fields=[
                ('cod_credito', models.IntegerField(primary_key=True, serialize=False)),
                ('articulo', models.CharField(max_length=30)),
                ('costo_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.IntegerField(default=12)),
                ('costo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(default='/creditos/default.jpg', upload_to='creditos')),
                ('pagada', models.CharField(default=0, max_length=1)),
                ('saldo_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
                ('quincena', models.IntegerField(default=1)),
                ('cod_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.entidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
